import threading

import nibbler.trading.collectors.futures_collector as f

ADA = threading.Thread(target=f.BinanceADA.ADAcollector)
ATOM = threading.Thread(target=f.BinanceATOM.ATOMcollector)
BAT = threading.Thread(target=f.BinanceBAT.BATcollector)
BCH = threading.Thread(target=f.BinanceBCH.BCHcollector)
BNB = threading.Thread(target=f.BinanceBNB.BNBcollector)
BTC = threading.Thread(target=f.BinanceBTC.BTCcollector1m)
DASH = threading.Thread(target=f.BinanceDASH.DASHcollector)
EOS = threading.Thread(target=f.BinanceEOS.EOScollector)
ETC = threading.Thread(target=f.BinanceETC.ETCcollector)
ETH = threading.Thread(target=f.BinanceETH.ETHcollector)
IOST = threading.Thread(target=f.BinanceIOST.IOSTcollector)
IOTA = threading.Thread(target=f.BinanceIOTA.IOTAcollector)
LINK = threading.Thread(target=f.BinanceLINK.LINKcollector)
LTC = threading.Thread(target=f.BinanceLTC.LTCcollector)
NEO = threading.Thread(target=f.BinanceNEO.NEOcollector)
ONT = threading.Thread(target=f.BinanceONT.ONTcollector)
QTUM = threading.Thread(target=f.BinanceQTUM.QTUMcollector)
THETA = threading.Thread(target=f.BinanceTHETA.THETAcollector1m)
TRX = threading.Thread(target=f.BinanceTRX.TRXcollector)
VET = threading.Thread(target=f.BinanceVET.VETcollector)
XLM = threading.Thread(target=f.BinanceXLM.XLMcollector)
XMR = threading.Thread(target=f.BinanceXMR.XMRcollector)
XRP = threading.Thread(target=f.BinanceXRP.XRPcollector)
XTZ = threading.Thread(target=f.BinanceXTZ.XTZcollector)
ZEC = threading.Thread(target=f.BinanceZEC.ZECcollector)

ADA.start()
ATOM.start()
BAT.start()
BCH.start()
BNB.start()
BTC.start()
DASH.start()
EOS.start()
ETH.start()
IOST.start()
IOTA.start()
LINK.start()
LTC.start()
NEO.start()
ONT.start()
QTUM.start()
THETA.start()
TRX.start()
VET.start()
XLM.start()
XMR.start()
XRP.start()
XTZ.start()
ZEC.start()